mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers
from novelrecorder import views
from novelrecorder.views import redirect_novelRecorder

urlpatterns = [
    path('', redirect_novelRecorder),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('novelrecorder/', include('novelrecorder.urls')),
    path('admin/', admin.site.urls),
    # Add Django site authentication urls (for login, logout, password management)
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.UserRegisterView.as_view(), name='register'),
]

novelrecorder/urls.py
from django.urls import path, re_path
from novelrecorder import views

app_name = 'novelrecorder'

urlpatterns = [
    # ex: /novelrecorder/
    path('', views.index, name='index'),
    # Novel
    path('public_novel_list/', views.PublicNovelListView.as_view(), name='public_novel_list'),
    path('my_novel_list/', views.UserNovelListView.as_view(), name='my_novel_list'),
    path('novel_detail/<int:pk>/', views.NovelDetailView.as_view(), name='novel_detail'),
    path('novel_detail_create/', views.NovelDetailCreateView.as_view(), name='novel_detail_create'),
    # Character
    path('character_detail/<int:pk>/', views.CharacterDetailView.as_view(), name='character_detail'),
    path('character_detail_delete/<int:pk>/', views.CharacterDetailDeleteView.as_view(), name='character_detail_delete'),
    path('character_detail_create/', views.CharacterDetailCreateView.as_view(), name='character_detail_create'),
    # Relationship
    path('relationship_detail/<int:pk>/', views.RelationshipDetailView.as_view(), name='relationship_detail'),
    path('relationship_detail_delete/<int:pk>/', views.RelationshipDetailDeleteView.as_view(), name='relationship_detail_delete'),
    path('relationship_detail_create/', views.RelationshipDetailCreateView.as_view(), name='relationship_detail_create'),
    # Description
    path('description_list_character/<int:character_id>/', views.DescriptionListCharacterView.as_view(), name='description_list_character'),
    path('description_list_relationship/<int:relationship_id>/', views.DescriptionListRelationshipView.as_view(), name='description_list_relationship'),
    path('description_detail/<int:pk>/', views.DescriptionDetailView.as_view(), name='description_detail'),
    path('description_detail_delete/<int:pk>/', views.DescriptionDetailDeleteView.as_view(), name='description_detail_delete'),
    path('description_detail_create/', views.DescriptionDetailCreateView.as_view(), name='description_detail_create'),
]

novelrecorder/views.py
from django.http import Http404
from rest_framework import status, serializers
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import render, redirect

from django.shortcuts import get_object_or_404
import django.urls
from django.views.generic import ListView
from rest_framework import generics
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response

from novelrecorder.models import NovelUser, Relationship
from novelrecorder.models import Novel
from novelrecorder.models import Character
from novelrecorder.models import Description
import novelrecorder.permissions
from novelrecorder.serializers import NovelSerializer, NovelReadOnlySerializer, \
    CharacterSerializer, CharacterReadOnlySerializer, CharacterWithPrimaryDescriptionSerializer, DescriptionSerializer, \
    DescriptionReadOnlySerializer, DescriptionCreateSerializer, CharacterCreateSerializer, \
    CharacterWithPrimaryDescriptionSlaveSerializer, DescriptionSlaveSerializer, RelationshipSerializer, \
    RelationshipReadOnlySerializer, RelationshipWithPrimaryDescriptionSerializer, RelationshipCreateSerializer, \
    RelationshipWithPrimaryDescriptionSlaveSerializer, UserRegisterSerializer, DescriptionPartialUpdateSerializer, \
    RelationshipPartialUpdateSerializer

from novelrecorder.yd_exceptions import DataErrorException


# Generic
class CustomHTMLViewMixin(object):
    renderer_classes = [TemplateHTMLRenderer]
    style = {'template_pack': 'rest_framework/vertical/'}

    def get_queryset(self):
        return self.model_class.objects.all()


class CustomNovelMixin(CustomHTMLViewMixin):
    permission_classes = [novelrecorder.permissions.NovelUserPermission]
    _model_class = None
    _data_name_single = ''
    _data_name_plural = ''
    _writable_serializer = None
    _read_only_serializer = None

    def get_model_class(self):
        assert self._model_class, 'Class %s._model_class is not set.' % self.__class__.__name__
        return self._model_class

    def get_data_name_single(self):
        assert self._data_name_single != '', 'Class %s._data_name_single is not set.' % self.__class__.__name__
        return self._data_name_single

    def get_data_name_plural(self):
        assert self._data_name_plural != '', 'Class %s._data_name_plural is not set.' % self.__class__.__name__
        return self._data_name_plural

    def get_writable_serializer(self):
        assert self._writable_serializer, 'Class %s._writable_serializer is not set.' % self.__class__.__name__
        return self._writable_serializer

    def get_read_only_serializer(self):
        assert self._read_only_serializer, 'Class %s._read_only_serializer is not set.' % self.__class__.__name__
        return self._read_only_serializer

    def has_write_permission(self):
        return True

    def get_serializer_class(self):
        if self.has_write_permission():
            return self.get_writable_serializer()
        else:
            return self.get_read_only_serializer()

    def get_serializer_context(self):
        context = super().get_serializer_context()
        context.update({'has_write_permission': self.has_write_permission()})
        return context

    model_class = property(get_model_class)
    data_name_single = property(get_data_name_single)
    data_name_plural = property(get_data_name_plural)
    read_only_serializer = property(get_read_only_serializer)
    writable_serializer = property(get_writable_serializer)


class CustomNovelRetrieveMixin(CustomNovelMixin):
    def get(self, request, pk):
        instance = self.get_object()
        serializer = self.get_serializer(instance)
        return Response({'serializer': serializer, self.data_name_single: instance})


class CustomNovelListMixin(CustomNovelMixin):
    def get(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        return Response({'serializer': serializer, self.data_name_plural: self.get_queryset})


# Basically post and delete.
class CustomHTMLRedirectMixin(CustomHTMLViewMixin):
    url_to_redirect_reverse = ''

    # Override this if needs a custom redirect method other than just assigning url_to_redirect_reverse
    def on_redirect(self, serializer):
        return None

    def default_redirect(self, serializer):
        raise NotImplementedError('The class %s does not implement default_redirect() as a descendant of CustomHTMLRedirectMixin.') % self.__class__.__name__

    def do_redirect(self, serializer):
        custom_redirect = self.on_redirect(serializer)
        if custom_redirect:
            return custom_redirect
        elif self.url_to_redirect_reverse:
            return redirect(django.urls.reverse_lazy(self.url_to_redirect_reverse))
        else:
            return self.default_redirect(serializer)


class CustomHTMLUpdateMixin(CustomHTMLRedirectMixin):
    def default_redirect(self, serializer):
        return Response({'serializer': serializer, self.data_name_single: self.get_object()})

    def post(self, request, pk):
        instance = self.get_object()
        serializer = self.get_serializer(instance, data=request.data)
        if not serializer.is_valid():
            return Response({'serializer': serializer, self.data_name_single: instance})
        serializer.save()
        return self.do_redirect(serializer)


class CustomHTMLCreateMixin(CustomHTMLRedirectMixin):
    def get(self, request):
        serializer = self.get_serializer()
        return Response({'serializer': serializer, 'style': self.style})

    def default_redirect(self, serializer):
        return Response({'serializer': serializer}, status=status.HTTP_201_CREATED)

    def post(self, request):
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return self.do_redirect(serializer)
        else:
            return Response({'serializer': serializer}, status=status.HTTP_400_BAD_REQUEST)


class CustomHTMLDeleteMixin(CustomHTMLRedirectMixin):
    def default_redirect(self, serializer): # TODO: Don't think would work as clashing with Update too, need to do something. But does it need one?
        return Response({'serializer': serializer}, status=status.HTTP_204_NO_CONTENT)

    # For validation and raise validation exception here
    def pre_delete(self, serializer):
        return True

    # Delete
    def post(self, request, pk):
        serializer = self.get_serializer(data=request.data)
        try:
            self.pre_delete(serializer)
        except Exception as e:
            return self.do_redirect(serializer) # TODO: redirect back without any error message for now.
        super().delete(self, request)
        return self.do_redirect(serializer)


class CustomNovelUpdateMixin(CustomNovelMixin, CustomHTMLUpdateMixin):
    pass


class CustomNovelCreateMixin(CustomNovelMixin, CustomHTMLCreateMixin):
    pass


class CustomNovelDeleteMixin(CustomNovelMixin, CustomHTMLDeleteMixin):
    pass


class CustomNovelRUDDetailView(CustomNovelRetrieveMixin, CustomNovelUpdateMixin, CustomNovelDeleteMixin, generics.RetrieveUpdateDestroyAPIView):
    class Meta:
        abstract = True

    def has_write_permission(self):
        for permission in self.permission_classes:
            permissionObj = permission()
            if isinstance(permissionObj, novelrecorder.permissions.NovelUserPermission):
                if not permission.custom_has_object_permission(permissionObj, self.request.user, True, self.get_object()):
                    return False
        return True

    def get_queryset(self):
        return self.model_class.objects.all()


class CustomNovelListCreateView(CustomNovelListMixin, generics.ListCreateAPIView):
    query_param_names = [] # The query param names need to be passed to the GET request for the create page

    class Meta:
        abstract = True

    def get_filter_object(self):
        raise NotImplementedError('Class %s.get_filter_object is not implemented.' % self.__class__.__name__)

    def has_write_permission(self):
        for permission in self.permission_classes:
            permissionObj = permission()
            if isinstance(permissionObj, novelrecorder.permissions.NovelUserPermission):
                if not permission.custom_has_object_permission(permissionObj, self.request.user, True, self.get_filter_object()):
                    return False
        return True

    def get_queryset(self):
        raise NotImplementedError('Class %s.get_queryset is not implemented.' % self.__class__.__name__)

    def get_serializer_context(self):
        context = super(CustomNovelListCreateView, self).get_serializer_context()
        for param_name in self.query_param_names:
            context.update({
                param_name: self.kwargs[param_name]
            })
        return context


@method_decorator(login_required, name='dispatch')
class CustomNovelCreateView(CustomNovelCreateMixin, generics.CreateAPIView):
    # Note that _read_only_serializer shouldn't be reached, but overriding it here won't do as in the multiple inheritance this comes after the "Model"Mixins.
    class Meta:
        abstract = True


@method_decorator(login_required, name='dispatch')
class CustomNovelDeleteView(CustomNovelDeleteMixin, generics.DestroyAPIView):
    class Meta:
        abstract = True


# Accounts
class UserRegisterView(CustomHTMLCreateMixin, generics.CreateAPIView):
    serializer_class = UserRegisterSerializer
    template_name = 'registration/register.html'
    url_to_redirect_reverse = 'login'


# Index
def index(request):
    # Generate dynamic contents
    num_novels = Novel.objects.all().count()
    num_characters = Character.objects.all().count()
    num_descriptions = Description.objects.count()
    num_relationships = Relationship.objects.count()

novelrecorder/templates/novelrecorder/character_detail.html
{% extends "base_generic.html" %}

{% load rest_framework %}

{% block content %}
<div class="master_character">
    <form action="{% url 'novelrecorder:character_detail' pk=character.pk %}" method="POST">
        {% csrf_token %}
        {% render_form serializer %}
        {% include "widgets/submit_save.html" %}
    </form>
    <form action="{% url 'novelrecorder:character_detail_delete' pk=character.pk %}" method="POST" onSubmit="return confirm('Are you sure you wish to delete this Character?\nThis will also delete all Descriptions it has.')">
        {% csrf_token %}
        <input type="hidden" value="{{ character.novel.id }}" name="novel_id">
        {% include "widgets/submit_delete.html" %}
    </form>
</div>
<br>
<div class="detail_description_list">
    {% include "novelrecorder/description_list_character.html" with character_id=character.pk %}
    <br>
    <form action="{% url 'novelrecorder:description_detail_create' %}">
        <input type="hidden" value="{{ character.pk }}" name="character_id">
        {% include "widgets/submit_new.html" with data_name="Description" %}
    </form>
</div>
<br>
<div class="relationship_list">
    {% include "novelrecorder/relationship_list.html" with character1_id=character.pk %}
    <br>
    <form action="{% url 'novelrecorder:relationship_detail_create' %}" id="relationship_detail_create_form">
        <input type="hidden" value="{{ character.pk }}" name="character1_id">
        {% include "widgets/submit_new.html" with data_name="Relationship" %}
    </form>
    {% if serializer.context.has_write_permission %}
        With: <select name="character2_id" form="relationship_detail_create_form">
        {% for character in serializer.context.charactersWithoutRelationship %}
            <option value={{ character.pk }}>{{ character.name }}</option>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

novelrecorder/templates/novelrecorder/character_detail_create.html
{% extends "base_generic.html" %}

{% load rest_framework %}

{% block content %}

<h1>New Character</h1>

<form action="{% url 'novelrecorder:character_detail_create' %}" method="POST">
    {% csrf_token %}
    {% render_form serializer %}
    <input type="submit" value="Create">
</form>
{% endblock %}

novelrecorder/templates/novelrecorder/character_list.html
{% block content %}
<table>
    <tr>
        <th>Name</th>
        <th>Primary Description Title</th>
        <th>Primary Description Content</th>
    </tr>
    {% for character in serializer.context.characters %}
    <tr>
        <td><a href="{% url 'novelrecorder:character_detail' pk=character.pk %}">{{ character.name }}</a></td>
        <td>{{ character.primary_description_title }}</td>
        <td>{{ character.primary_description_content }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

novelrecorder/templates/novelrecorder/description_detail.html
{% extends "base_generic.html" %}

{% load rest_framework %}

{% block content %}
<form action="{% url 'novelrecorder:description_detail' pk=description.pk %}" method="POST">
    {% csrf_token %}
    {% render_form serializer %}
    {% include "widgets/submit_save.html" %}
</form>
<form action="{% url 'novelrecorder:description_detail_delete' pk=description.pk %}" method="POST"  onSubmit="return confirm('Are you sure you wish to delete this Description?')">
    {% csrf_token %}
    <input type="hidden" value="{{ description.character.id }}" name="character_id">
    {% include "widgets/submit_delete.html" %}
</form>
{% endblock %}

novelrecorder/templates/novelrecorder/description_detail_create.html
{% extends "base_generic.html" %}

{% load rest_framework %}

{% block content %}

<h1>New Description</h1>

{{ character }}

<form action="{% url 'novelrecorder:description_detail_create' %}" method="POST">
    {% csrf_token %}
    {% render_form serializer %}
    <input type="submit" value="Create">
</form>
{% endblock %}

novelrecorder/templates/novelrecorder/description_list_character.html
{% block content %}
<table>
    <tr>
        <th>Title</th>
        <th>Content</th>
    </tr>
    {% for description in serializer.context.descriptions %}
    <tr>
        <td>{% if forloop.first %}<b>{% endif %}
            <a href="{% url 'novelrecorder:description_detail' pk=description.pk %}">{{ description.title }}</a>
        {% if forloop.first %}</b>{% endif %}</td>
        <td>{{ description.content }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

novelrecorder/templates/novelrecorder/description_list_relationship.html
{% block content %}
<table>
    <tr>
        <th>Title</th>
        <th>Content</th>
    </tr>
    {% for description in serializer.context.descriptions %}
    <tr>
        <td>{% if forloop.first %}<b>{% endif %}
            <a href="{% url 'novelrecorder:description_detail' pk=description.pk %}">{{ description.title }}</a>
        {% if forloop.first %}</b>{% endif %}</td>
        <td>{{ description.content }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

novelrecorder/templates/novelrecorder/my_novel_list.html
{% extends "base_generic.html" %}

{% load rest_framework %}

{% block content %}

<h2>My novels</h2>
<br>
<table>
    <tr>
        <th><b>Name</b></th>
        <th><b>Author</b></th>
        <th><b>Is Public?</b></th>
    </tr>
    {% for novel in novels %}
    <tr>
        <td><a href="{% url 'novelrecorder:novel_detail' pk=novel.id %}">{{ novel.name }}</a></td>
        <td>{{ novel.author }}</td>
        <td><input type="checkbox" {% if novel.is_public %} checked {% endif %} disabled></td>
    </tr>
    {% endfor %}
</table>
<br>

<form action="{% url 'novelrecorder:novel_detail_create' %}">
    {% include "widgets/submit_new.html" with data_name="Novel" %}
</form>
{% endblock %}

novelrecorder/templates/novelrecorder/novel_detail.html
{% extends "base_generic.html" %}
{% load rest_framework %}

{% block content %}
<h1>{{ novel.name }}</h1>
<div class="master_novel">
    <form action="{% url 'novelrecorder:novel_detail' pk=novel.pk %}" method="POST">
        {% csrf_token %}
        {% render_form serializer %}
        {% include "widgets/submit_save.html" %}
    </form>
</div>
<br>
<div class="detail_character_list">
    {% include "novelrecorder/character_list.html" with novel_id=novel.pk %}
    <br>
    <form action="{% url 'novelrecorder:character_detail_create' %}">
        <input type="hidden" value="{{ novel.pk }}" name="novel_id">
        {% include "widgets/submit_new.html" with data_name="Character" %}
    </form>
</div>
{% endblock %}

novelrecorder/templates/novelrecorder/novel_detail_create.html
{% extends "base_generic.html" %}

{% load rest_framework %}

{% block content %}
<h1>New Novel</h1>

<form action="{% url 'novelrecorder:novel_detail_create' %}" method="POST">
    {% csrf_token %}
    {% render_form serializer %}
    <input type="submit" value="Create">
</form>
{% endblock %}

novelrecorder/templates/novelrecorder/public_novel_list.html
{% extends "base_generic.html" %}

{% block content %}
<h2>All public novels</h2>
<br>
<table>
    <tr>
        <th><b>Name</b></th>
        <th><b>Author</b></th>
    </tr>
    {% for novel in public_novel_list %}
    <tr>
        <td><a href="{% url 'novelrecorder:novel_detail' pk=novel.id %}">{{ novel.name }}</a></td>
        <td>{{ novel.author }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

novelrecorder/templates/novelrecorder/relationship_detail.html
{% extends "base_generic.html" %}

{% load rest_framework %}

{% block content %}
<div class="master_relationship">
    <form action="{% url 'novelrecorder:relationship_detail' pk=relationship.pk %}" method="POST">
        {% csrf_token %}
        {% render_form serializer %}
        {% include "widgets/submit_save.html" %}
    </form>
    <form action="{% url 'novelrecorder:relationship_detail_delete' pk=relationship.pk %}" method="POST" onSubmit="return confirm('Are you sure you wish to delete this Relationship?\nThis will also delete all Descriptions it has.')">
        {% csrf_token %}
        <input type="hidden" value="{{ relationship.character1.id }}" name="character1_id">
        {% include "widgets/submit_delete.html" %}
    </form>
</div>
<br>
<div class="detail_description_list">
    {% include "novelrecorder/description_list_relationship.html" with relationship_id=relationship.pk %}
    <br>
    <form action="{% url 'novelrecorder:description_detail_create' %}">
        <input type="hidden" value="{{ relationship.pk }}" name="relationship_id">
        {% include "widgets/submit_new.html" with data_name="Description" %}
    </form>
</div>
{% endblock %}

novelrecorder/templates/novelrecorder/relationship_detail_create.html
{% extends "base_generic.html" %}

{% load rest_framework %}

{% block content %}

<h1>New Relationship</h1>

<form action="{% url 'novelrecorder:relationship_detail_create' %}" method="POST">
    {% csrf_token %}
    {% render_form serializer %}
    <input type="submit" value="Create">
</form>
{% endblock %}

novelrecorder/templates/novelrecorder/relationship_list.html
{% block content %}
<table>
    <tr>
        <th>Relationship</th>
        <th>Object Character</th>
        <th>Primary Description Title</th>
        <th>Primary Description Content</th>
    </tr>
    {% for relationship in serializer.context.relationships %}
    <tr>
        <td><a href="{% url 'novelrecorder:relationship_detail' pk=relationship.pk %}">{{ relationship.relationship_display }}</a></td>
        <td><a href="{% url 'novelrecorder:character_detail' pk=relationship.character2_id %}">{{ relationship.character2_name }}</a></td>
        <td>{{ relationship.primary_description_title }}</td>
        <td>{{ relationship.primary_description_content }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}